### ISSUE TITLE
Microphone-speaker "problem"

### ISSUE THREAD

**Issue by sp5wwp** [M17-Project/Mini17#14]
We need a different type of 3.5 and 2.5mm jack connectors to support both internal and external microphone/speaker. See the image below for details (that's a part of TYT MD-380 handheld transceiver).
![image](https://user-images.githubusercontent.com/44336093/182032115-979d565c-4cec-4f25-802c-5c5372ea6965.png)

**Comment by JKI757** [comment]
Ok here's a 3.5mm that lines up with what you're looking for here I *think*.

https://www.digikey.com/en/products/detail/STX-3200-5NB/2092-STX-3200-5NB-ND/10246571

**Comment by JKI757** [comment]
And this looks like a possible for the 2.5mm:

https://www.digikey.ca/en/products/detail/cui-devices/SJ2-25313D-SMT-TR/6619292

**Comment by JKI757** [comment]
> Ok here's a 3.5mm that lines up with what you're looking for here I *think*.
> 
> 
> 
> https://www.digikey.com/en/products/detail/STX-3200-5NB/2092-STX-3200-5NB-ND/10246571

Use this one instead as it's available in lcsc per discussion in chat:

https://www.lcsc.com/product-detail/Audio-Connectors_BOOMELE-Boom-Precision-Elec-PJ-307C_C16684.html

**Comment by sp5wwp** [comment]
Schematic fixed.
