### ISSUE TITLE
Should we use an open-source alternative to CubeIDE?

### ISSUE THREAD

**Issue by uranuspucksaxophone** [M17-Project/Mini17#28]

**Comment by JKI757** [comment]
CubeIDE is an ST configured version of Eclipse packaged up with GDB.  

CubeMX simply provides configuration info for the MCU.  There's no requirement to use it, and the existing codebases people anticipate putting on here as far as I know aren't based on it. Even if they are, I don't think it matters.  

The use of CubeMX/CubeIDE doesn't "infect" anything with regard to licensing, at least not that I'm aware of. 

The presence of the .ioc file doesn't place any constraints on anyone -- I'm using CubeMX just a tool to assist in validating schematic design and I'll probably create some test firmware with it at some point as well.  It saves a ton of time in figuring out what pins are compatible with what signals and where to put them for better routing on the PCB as well. 

IOW don't read too much into the existence of an ioc file -- it's just a tool.

**Comment by sp5wwp** [comment]
This file is only used for setting pin configuration.
